const mongoose = require('mongoose');

/**
 * Deadline — a statutory or self-imposed date the user needs to act on
 * (advance tax installment, ITR filing, GST return, etc). Generated by
 * POST /api/deadlines/run, not created directly by users.
 */
const deadlineSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    type: { type: String, enum: ['advance_tax', 'filing', 'gst', 'other'], required: true },
    label: { type: String, required: true, trim: true },
    dueDate: { type: Date, required: true },
    status: { type: String, enum: ['upcoming', 'completed'], default: 'upcoming' },
    estimatedAmount: { type: Number, default: null },
    relatedEstimateId: { type: mongoose.Schema.Types.ObjectId, ref: 'TaxEstimate', default: null },
    notified: { type: Boolean, default: false },
  },
  { timestamps: true },
);

deadlineSchema.index({ userId: 1, dueDate: 1 });
// One deadline per (user, type, dueDate) — re-running the generator is idempotent.
deadlineSchema.index({ userId: 1, type: 1, dueDate: 1 }, { unique: true });

module.exports = mongoose.model('Deadline', deadlineSchema);
